### ISSUE TITLE
Mentorship Idea

### ISSUE THREAD

**Issue by iamjessklein** [bocoup/skillsbot#18]
I am personally interested in identifying mentorship opportunities using the bot. I discussed this with @cowboy and one way that he suggested I tackle this is by creative a report using the _existing data_.

Specifically I am imagining creating a report using the list of existing data to pair those who want to learn with those who have expertise.

Thoughts? I'm interested in prototyping this. @tkellen @cowboy @boazsender

**Comment by cowboy** [comment]
_Interest:_​

> ​_1._​ I really dislike this. Please do not ask me about this.
> ​_2._​ I would like to avoid this if possible.
> ​_3._​ I have no feelings for or against this.
> ​_4._​ I like this.
> ​_5._​ I love this. Please ask me about this!

​_Experience:_​

> ​_1._​ I have no experience with this.
> ​_2._​ I have some experience but I am not yet confident with this.
> ​_3._​ I have some experience and feel confident with this.
> ​_4._​ I have lots of experience and can teach others this.
> ​_5._​ I would feel comfortable having a team of people rely on me for this.

Given these scales, what if we created a report that found all people with an **interest** of 4-5 for a given expertise and suggested those with **experience** of 4-5 act as mentors for those with **experience** of 1-2?

**Comment by iamjessklein** [comment]
👍  that sounds like a perfect first report.

 My follow up question is : who is interested in mentoring? I'm taking a look at the database and there is a "Coaching" expertise under the category of "Education". I think that we should either use the interest ( 4- 5) and experience (4 - 5) as an indicator for mentorship ability _or_ we should make a mentorship expertise under Education. Thoughts?
