### ISSUE TITLE
Remove slack_user and slack_channel tables?

### ISSUE THREAD

**Issue by cowboy** [bocoup/skillsbot#19]
Right now, the `slack_channel` table is unused, because the bot doesn't have any per-channel state. I don't see it being used, so it can easily be dropped.

The `slack_user` table is mostly redundant, because it stores a Slack User ID (eg. `U03BS5P65`) along with an `id` for foreign key joining, and a `name` (eg. `cowboy`) that we don't need to store because we can query Slack for that. We can get a Slack User ID from a Slack username, and we can get all user Slack metadata from the Slack User ID by querying Slack.
- If we use this table, we'll need to ensure that names and ids stay in sync, and that we build a system for adding and deleting (or setting active/inactive) users.
- If we don't use this table, we'll need to store the slack User ID instead of `slack_user.id` foreign key everywhere, and just query Slack for user data like `name` for bot output.

**Comment by tkellen** [comment]
If this eliminates complexity without affecting your implementation, I say go for it. We can easily add it back if needed.

**Comment by cowboy** [comment]
Per conversation with @tkellen, I'll just remove the `slack_channel` table and remove the `slack_user` table `name` field since they aren't currently used.

I'll file a separate issue about augmenting the `slack_users` table and creating a `sync users` command.

**Comment by cowboy** [comment]
I'm just going to remove the `slack_channel` table in this issue, and address the `slack_user` stuff in #22.
