### ISSUE TITLE
How should user names be displayed?

### ISSUE THREAD

**Issue by cowboy** [bocoup/skillsbot#20]
I'm not sure what to do here. Displaying team member names should be consistent across all the bot's command output, but it's a little challenging.
- The "real name" can be long, and isn't required to be filled out by slack users
- The slack username is usually a shorter name than someone's real name.
- The slack username may or may not be how someone views messages by default (this is configurable in per-user settings)
- Formatted (and clickable) slack usernames can be clicked for more information about that user, which is pretty nice.

We could display the slack username:

![](https://i.gyazo.com/d274ed67ee62d2b0fa99b88285ff2fa4.png)

We could display the "real name" which unfortunately many people haven't filled in:

![](https://i.gyazo.com/d897b4efc73d90995ff7fe6ecc1337e6.png)

We could display the "real name" and then fall back to slack username:

![](https://i.gyazo.com/1c49ac17f06ebfb7d7dc8c3ae013a619.png)

We could display a formatted (and clickable) slack username:

![](https://i.gyazo.com/9b847fb85a782806268d960160b0bed0.png)

**Comment by iamjessklein** [comment]
i'm tempted to say slack username because that would also solve the issue of potential duplication of names (2 users named jess).

**Comment by cowboy** [comment]
Yeah. if we use formatted Slack names throughout, they can be clicked for a popup with info, like so:

![](https://i.gyazo.com/3416c0abb5f61f05c89a4b184b23c192.png)

**Comment by cowboy** [comment]
I'm going to use formatted Slack names throughout and see how things go. Feel free to comment if you have any suggestions.
