### ISSUE TITLE
Use token instead of teamId in queries

### ISSUE THREAD

**Issue by cowboy** [bocoup/skillsbot#26]
Because the `slack_team` table can have multiple rows with the same `slack_id`, but the `token` is always unique, I think it makes more sense to join on the `token` and not `slack_id` (`teamId`) in the following queries:

https://github.com/bocoup/expertisebot/blob/master/src/sql/expertise_by_name.sql
https://github.com/bocoup/expertisebot/blob/master/src/sql/categories_and_expertises.sql

@tkellen thoughts?

**Comment by tkellen** [comment]
what's the case where there are multiple entries for a given slack_id?

**Comment by cowboy** [comment]
Whenever you remove an integration from a team and then re-add it. I don't expect it to happen often, but it'll certainly happen here or there. And I've done it half a dozen times while testing.

**Comment by tkellen** [comment]
can we avoid inserting a new team and instead flag a team who left as inactive/active?

**Comment by cowboy** [comment]
It was part of the design to only add new teams, and set inactive teams as inactive. We could totally change it to upsert teams, though.

**Comment by cowboy** [comment]
(Expertisebot and Pombot do the same thing here)

**Comment by tkellen** [comment]
let's do that! i don't want to tie our foreign key relationships to data we don't control.

**Comment by cowboy** [comment]
Not sure I understand. We store both the token and the Slack Team Id in that table. And we get both of those values at runtime. What data do we not control?
