### ISSUE TITLE
Write usability test script

### ISSUE THREAD

**Issue by iamjessklein** [bocoup/skillsbot#63]
As per issue #11 - we need to write usability tests to evaluate the effectiveness of the current naming system for commands.

**Comment by iamjessklein** [comment]
I started to draft the usability test script in this [markdown file](https://github.com/bocoup/skillsbot/blob/master/command-naming-testscript.md)

**Comment by iamjessklein** [comment]
I have a draft written [here](https://github.com/bocoup/skillsbot/blob/master/command-naming-testscript.md) 

@cowboy - can you review the script today? If you have any changes, make them and submit them as a PR.

**Comment by iamjessklein** [comment]
@cowboy - R? the latest script.

**Comment by cowboy** [comment]
This looks good to me 👍 
https://github.com/bocoup/skillsbot/wiki/Command-Naming-Test-Script
