### ISSUE TITLE
Editing a previous find leads to a skill menu being printed?

### ISSUE THREAD

**Issue by gnarf** [bocoup/skillsbot#66]
![skillsbot-bug](https://cloud.githubusercontent.com/assets/549355/17153422/b1f908d0-534a-11e6-8259-610441440044.gif)

**Comment by cowboy** [comment]
There is a known issue where sometimes a bot gets into a state where editing text causes a dialog message to display. I'm going to bounce the bot tonight. Tomorrow, can you try again and see if you can reproduce this?

**Comment by cowboy** [comment]
@gnarf can you try this again? Is it reproducible?

**Comment by gnarf** [comment]
Works as expected this morning.  Do you know how I got the bot into that state, should I try to reproduce it?

**Comment by cowboy** [comment]
I've been trying to reproduce this, but I have NO idea how the bot gets into this state. But it's happened before:
1. Someone edits a slack message in a DM with the bot or a public channel the bot is in
2. The bot shows a "detached" dialog message, that doesn't actually wait for user input

Once the bot gets into this state, it seems to happen every time, although I don't know if it happens in every channel. That should be tested if we can reproduce this.

**Comment by cowboy** [comment]
Anything you can do to help troubleshoot would be helpful. It seems to have something to do with the chatter dialog system, so it's probably related to the `update` command.
