### ISSUE TITLE
Edit the help description text to have less redundancy

### ISSUE THREAD

**Issue by iamjessklein** [bocoup/skillsbot#70]
<img width="610" alt="screen shot 2016-07-28 at 3 25 52 pm" src="https://cloud.githubusercontent.com/assets/535012/17226457/986dbdf0-54d7-11e6-90a0-30114ee84b78.png">

**Comment by cowboy** [comment]
@iamjessklein, can you take a pass at editing these this morning? If you add them into a comment, I'll change them in the code.

> **skill** - List all team members with the given skill, grouped by interest and experience.
> **user** - List all skills for the given team member, grouped by interest and experience.
> **me** - List all of your skills, grouped by interest and experience.
> **list** - List all skills, grouped by category.
> **scales** - List interest and experience scales.
> **stats** - Provide statistics about a given skill.
> **update** - Update your interest and experience for the given skill.

**Comment by cowboy** [comment]
Also, feel free to change the order!
