### ISSUE TITLE
Write more thorough “help” text so that when people type “help for” (per the bot’s own suggestion) they get more than just the command description

### ISSUE THREAD

**Issue by iamjessklein** [bocoup/skillsbot#74]
<img width="296" alt="screen shot 2016-07-27 at 10 40 48 am" src="https://cloud.githubusercontent.com/assets/535012/17226679/98703142-54d8-11e6-997a-0df2c40c59da.png">

**Comment by cowboy** [comment]
Every command can have a `details` property that will be displayed after the description, usage info, and possible sub-commands when `help` is used. And this message can be any length and have any Slack formatting!
