### ISSUE TITLE
Greedy Regex

### ISSUE THREAD

**Issue by MattSurabian** [bocoup/skillsbot#81]
![image](https://cloud.githubusercontent.com/assets/1134260/17374493/dede8e20-597a-11e6-9722-244da3fea570.png)

Fuzzy search is well and good but this is maybe too fuzzy

**Comment by cowboy** [comment]
Right now, we're just using `ILIKE '%git%'` in the SQL query, but additional logic could be added in the JavaScript to further filter out bad matches.

Here's a basic example:

``` js
const search = 'git';
const queryResults = ['Git', 'Digital', 'My Git Example', 'Gitosis'];

const re = new RegExp(`\\b${search}`, 'i');
const filteredResults = queryResults.filter(s => re.test(s));

filteredResults // ["Git", "My Git Example", "Gitosis"]
```
