### ISSUE TITLE
Prompt differently for new skills tracked vs onboarding

### ISSUE THREAD

**Issue by boazsender** [bocoup/skillsbot#88]
In #87 we made the "skills" missing work better in the context of new skills being added to track.

Consider branching this logic to give different prompts for when the org starts tracking a new skill versus, a new team member filling this out for the first time. Eg:

> we're tracking n new skills this week

**Comment by tkellen** [comment]
As a note, the heuristic we'd use for this would be if the person receiving the message has no skill values logged at all.
